name: xweather
description: check weather.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.0
  flutter:
    sdk: flutter

  flutter_launcher_icons: "^0.9.0"
  http: ^0.13.3

flutter_icons:
  image_path: "icon/icon.ico"
  android: true
  ios: true

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - icon/

  uses-material-design: true

  fonts:
    - family: Comfortaa
      fonts:
        - asset: google_fonts/Comfortaa-Regular.ttf
